### ISSUE TITLE
Breaks with Angular 5

### ISSUE THREAD

**Issue by Epenance** [NetanelBasal/ngx-text-equality-validator#3]
Seems to be breaking when upgrading to Angular 5 :(

> WARNING in ./node_modules/ngx-text-equality-validator/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Applications/Web/wishlist/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:701:24)
    at Compilation.finish (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:559:9)
    at applyPluginsParallel.err (/Applications/Web/wishlist/node_modules/webpack/lib/Compiler.js:506:17)
    at /Applications/Web/wishlist/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:505:11)
    at processModuleDependencies.err (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

> WARNING in ./node_modules/ngx-text-equality-validator/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/Applications/Web/wishlist/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:701:24)
    at Compilation.finish (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:559:9)
    at applyPluginsParallel.err (/Applications/Web/wishlist/node_modules/webpack/lib/Compiler.js:506:17)
    at /Applications/Web/wishlist/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:505:11)
    at processModuleDependencies.err (/Applications/Web/wishlist/node_modules/webpack/lib/Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by NetanelBasal** [comment]
I still do not work with Angular 5. If you can create a demo with [stackblitz](https://stackblitz.com), it will help.
